apiVersion: v1
kind: Namespace
metadata:
  name: mini-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mini-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mini-api
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mini-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: mini-api
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimalapi
  namespace: mini-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimalapi
  template:
    metadata:
      labels:
        app: minimalapi
    spec:
      containers:
      - name: minimalapi
        image: andersontmarquesbr/minimalapi:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://admin:password@mongodb-service:27017"
        - name: REDIS_CONNECTION_STRING
          value: "redis-service:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: minimalapi-service
  namespace: mini-api
spec:
  selector:
    app: minimalapi
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer